apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: myingress
spec:
  ingressClassName: nginx
#   rules:
#   # {{- range .Values.api.ingress }}
#   # - host: {{ . }}
    - http:
        paths:
        - backend:
            # serviceName: {{ $.Release.Name }}-api-service
            serviceName: minhaapi-api-service
            servicePort: 80
  # {{- end }}