api:
  image: carlosmendesrv/rotten-potatoes:latest
  #serviceType: LoadBalancer
  serviceType: ClusterIP
  ingress:
  - aulakubedev.com.br

mongodb:
  tag: 4.2.8
  #existSecret: nome do secret
  credentials:
    hostName: mongodb
    userName: mongouser
    userPassword: mongopwd
  databaseName: admin